services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      DISK_SIZE: "256G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      LANGUAGE: "Slovak"
      REGION: "en-US"
      KEYBOARD: "en-US"

    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /var/windows/volumes/windows10:/storage
